import "dotenv/config";
import { db } from "../db";
import { 
  fact_sales, 
  cash_register_transactions, 
  payment_gateways_ledger, 
  transactions, 
  products, 
  bom_recipes 
} from "../db/schema";
import { eq, inArray } from "drizzle-orm";
import Papa from "papaparse";
import * as xlsx from "xlsx";
import fs from "fs";
import path from "path";
import { z } from "zod";
import { randomUUID } from "node:crypto";
import { parseAndTransformTransactionsBulk } from "../schemas/transactions";

const SaleRowSchema = z.object({
  Fecha: z.any().transform(v => {
    if (!v) return "";
    if (typeof v === "number") {
      const step = v > 59 ? 25569 : 25568;
      return new Date((v - step) * 86400 * 1000).toISOString().split("T")[0];
    }
    return String(v).trim();
  }),
  "ID CAJA": z.coerce.string(),
  "Articulo Vendido": z.coerce.string(),
  Cantidad: z.any().transform(val => {
    if (typeof val === "number") return val;
    return Number(String(val).replace(/[^0-9.-]+/g,"")) || 0;
  }),
  "Precio / Valor": z.any().transform(val => {
    if (typeof val === "number") return val;
    return Number(String(val).replace(/[^0-9.-]+/g,"")) || 0;
  })
}).transform(data => {
  let qty = data.Cantidad;
  let desc = data["Articulo Vendido"].trim();
  let type: "PRODUCT" | "SERVICES_FEE" = "PRODUCT";
  let skipBOM = false;

  if (desc.toUpperCase() === "ENVIO" || desc.toUpperCase().includes("FEE")) {
    type = "SERVICES_FEE";
    skipBOM = true;
  } else {
    // Si viene en formato "2 x PRODUCTO", multiplicar
    const match = desc.match(/(\d+)\s*[xX]\s*(.*)/);
    if (match) {
      qty = qty * parseInt(match[1], 10);
      desc = match[2].trim();
    }
  }

  return {
    date: data.Fecha,
    register_num: data["ID CAJA"],
    raw_name: data["Articulo Vendido"],
    clean_name: desc,
    quantity: qty,
    gross_price: data["Precio / Valor"],
    type,
    skipBOM
  };
});

const DinamicaRowSchema = z.object({
  FechaCaja: z.coerce.string(),
  NroCaja: z.coerce.string(),
  Turno: z.coerce.string(),
  ImporteApertura: z.any().transform(v => Number(v) || 0),
  ImporteCierre: z.any().transform(v => Number(v) || 0),
  Diferencias: z.any().transform(v => Number(v) || 0),
  ImporteCobrado: z.any().transform(v => Number(v) || 0),
  Efectivo: z.any().transform(v => Number(v) || 0),
  MercadoPago: z.any().transform(v => Number(v) || 0),
  Delivery: z.any().transform(v => Number(v) || 0)
});

async function loadDictionaries() {
  const allProducts = await db.select().from(products).all();
  const skuMap = new Map<string, string>();
  for (const prod of allProducts) {
    skuMap.set(prod.name.toUpperCase(), prod.id);
    if (prod.synonyms && Array.isArray(prod.synonyms)) {
      prod.synonyms.forEach(syn => skuMap.set(syn.toUpperCase(), prod.id));
    }
  }

  const allBom = await db.select().from(bom_recipes).all();
  const bomMap = new Map<string, typeof allBom>();
  for (const item of allBom) {
    if(!item.product_sku) continue;
    if (!bomMap.has(item.product_sku)) bomMap.set(item.product_sku, []);
    bomMap.get(item.product_sku)!.push(item);
  }
  return { skuMap, bomMap, allProducts: new Set(allProducts.map(p => p.id)) };
}

async function ensureProductExists(skuSet: Set<string>, skuIds: Set<string>) {
  const missing = Array.from(skuIds).filter(id => !skuSet.has(id));
  if (missing.length > 0) {
    console.log(`[ETL] Creando ${missing.length} productos faltantes para sortear FK constraints...`);
    const newProducts = missing.map(id => ({
      id,
      name: id,
      unit: "UNIDAD" as const,
      category: "SIDE" as const,
      base_price_cents: 0,
      description: "Auto-generated by ETL Phase 80 to satisfy Foreign Keys",
      isSaleable: false,
    }));
    for (let i = 0; i < newProducts.length; i += 500) {
       await db.insert(products).values(newProducts.slice(i, i + 500));
    }
    missing.forEach(id => skuSet.add(id));
  }
}

async function ingestSales(filePath: string, dicts: { skuMap: Map<string, string>, bomMap: Map<string, any[]>, allProducts: Set<string> }) {
  if (!fs.existsSync(filePath)) {
    console.log(`[ETL] Archivo no encontrado: ${filePath}`);
    return;
  }
  const { skuMap, bomMap, allProducts } = dicts;
  
  const workbook = xlsx.readFile(filePath);
  const sheetName = workbook.SheetNames[0];
  const rawCsvData = xlsx.utils.sheet_to_json<any>(workbook.Sheets[sheetName], { defval: "", range: 1 });

  // 0. Normalizador Inmune (Fuzzy Key Matcher)
  const normalizeRowKeys = (row: any) => {
    const normalized: any = {};
    for (const key of Object.keys(row)) {
      let cleanKey = String(key).trim().toUpperCase();
      if (cleanKey.includes("FECHA")) normalized.Fecha = row[key];
      else if (cleanKey.includes("CAJA") && (cleanKey.includes("ID") || cleanKey.includes("NRO"))) normalized["ID CAJA"] = row[key];
      else if (cleanKey.includes("ARTICULO") || cleanKey.includes("DESCRIP")) normalized["Articulo Vendido"] = row[key];
      else if (cleanKey.includes("CANTIDAD")) normalized.Cantidad = row[key];
      else if (cleanKey.includes("PRECIO") || cleanKey.includes("VALOR") || cleanKey.includes("IMPORTE")) normalized["Precio / Valor"] = row[key];
      else normalized[key] = row[key];
    }
    // Retener la data cruda también por las dudas
    return { ...row, ...normalized };
  };

  // 1. Memorias independientes para el "Fill Down"
  let currentFechaCaja: any = "";
  let currentNroCaja: any = "";

  const normalizedData = rawCsvData.map((rawRow) => {
    const row = normalizeRowKeys(rawRow);

    // A. Actualiza la fecha SOLO si la celda tiene una fecha nueva
    if (row.Fecha !== undefined && row.Fecha !== "") {
      currentFechaCaja = row.Fecha;
    }

    // B. Actualiza la caja SOLO si la celda tiene una caja nueva
    if (row["ID CAJA"] !== undefined && row["ID CAJA"] !== "") {
      currentNroCaja = row["ID CAJA"];
    }

    // C. Protege la cantidad: Si viene vacía (ej: ENVIO), asume que es 1
    const cantidadCruda = row.Cantidad;
    const cantidadFinal = (cantidadCruda !== undefined && String(cantidadCruda).trim() !== "") 
                          ? Number(String(cantidadCruda).replace(/[^0-9.-]+/g,"")) 
                          : 1;

    // Retornamos la fila perfectamente reconstruida
    return {
      ...row,
      Fecha: currentFechaCaja,
      "ID CAJA": currentNroCaja,
      Cantidad: cantidadFinal
    };
  });

  const factSalesBatch: any[] = [];
  const transactionsBatch: any[] = [];
  const requiredSkus = new Set<string>();
  
  for (const row of normalizedData) {
    try {
      const cleanRow = SaleRowSchema.parse(row);
      let targetSku = "MISC_UNKNOWN";
      
      if (cleanRow.type === "PRODUCT") {
        targetSku = skuMap.get(cleanRow.clean_name.toUpperCase()) || "MISC_UNKNOWN";
      } else {
         targetSku = "SRV_" + cleanRow.clean_name.toUpperCase().replace(/\s+/g, "_");
      }
      
      requiredSkus.add(targetSku);

      factSalesBatch.push({
        id: randomUUID(),
        date: cleanRow.date,
        shift: "UNKNOWN",
        raw_name: cleanRow.raw_name,
        productSku: targetSku,
        quantity: cleanRow.quantity,
        net_price_cents: Math.round(cleanRow.gross_price * 100),
      });

      if (!cleanRow.skipBOM && targetSku !== "MISC_UNKNOWN") {
        const recipe = bomMap.get(targetSku);
        if (recipe) {
          for (const item of recipe) {
            requiredSkus.add(item.ingredient_id!);
            transactionsBatch.push({
              date: cleanRow.date,
              type: "SALE",
              productSku: item.ingredient_id,
              quantity: -(item.theoretical_qty * cleanRow.quantity),
              referenceId: `BOM_EXPLOSION_${cleanRow.register_num}`,
              notes: `Consumo automático por venta de ${cleanRow.quantity}x ${cleanRow.clean_name}`,
            });
          }
        }
      }
    } catch (e) {}
  }

  await ensureProductExists(allProducts, requiredSkus);

  console.log(`[ETL] Inyectando ${factSalesBatch.length} Fact Sales y ${transactionsBatch.length} Movimientos BOM...`);
  
  const CHUNK_SIZE = 500;
  
  const safeFactSalesBulk = parseAndTransformTransactionsBulk(factSalesBatch);
  
  for (let i = 0; i < safeFactSalesBulk.length; i += CHUNK_SIZE) {
    await db.insert(fact_sales).values(safeFactSalesBulk.slice(i, i + CHUNK_SIZE));
  }
  for (let i = 0; i < transactionsBatch.length; i += CHUNK_SIZE) {
    await db.insert(transactions).values(transactionsBatch.slice(i, i + CHUNK_SIZE));
  }
}

async function ingestDynamics(filePath: string) {
  if (!fs.existsSync(filePath)) return;
  const file = fs.readFileSync(filePath, "utf-8");
  const parsed = Papa.parse<any>(file, { header: true, skipEmptyLines: true });
  
  const cashMap = new Map<string, any>();
  const gatewaysBatch: any[] = [];

  for (const row of parsed.data) {
    try {
      const cleanRow = DinamicaRowSchema.parse(row);
      
      const shiftUpper = cleanRow.Turno.toUpperCase();
      const hashKey = `${cleanRow.FechaCaja}-${cleanRow.NroCaja}-${shiftUpper}-MIXTO`;

      if (cashMap.has(hashKey)) {
        const existing = cashMap.get(hashKey);
        existing.amount += cleanRow.ImporteCobrado;
        cashMap.set(hashKey, existing);
      } else {
        cashMap.set(hashKey, {
          id: randomUUID(),
          date: cleanRow.FechaCaja,
          registerNum: cleanRow.NroCaja,
          shift: shiftUpper,
          openingAmount: cleanRow.ImporteApertura,
          closingAmount: cleanRow.ImporteCierre,
          discrepancy: cleanRow.Diferencias,
          cashInRegister: cleanRow.ImporteCierre + cleanRow.Diferencias, 
          paymentMethod: "MIXTO",
          amount: cleanRow.ImporteCobrado,
        });
      }

      if (cleanRow.MercadoPago > 0) {
        gatewaysBatch.push({
           id: randomUUID(),
           gateway: "MERCADO_PAGO",
           transactionReference: `CQ-${cleanRow.NroCaja}-MP`,
           date: cleanRow.FechaCaja,
           grossAmount: cleanRow.MercadoPago,
           netAmount: cleanRow.MercadoPago * 0.98,
           releaseDate: cleanRow.FechaCaja,
        });
      }
    } catch (e) {}
  }

  const cashBatch = Array.from(cashMap.values());
  console.log(`[ETL] Inyectando ${cashBatch.length} Cajas unificadas y ${gatewaysBatch.length} Pagos...`);
  
  const CHUNK_SIZE = 500;
  for (let i = 0; i < cashBatch.length; i += CHUNK_SIZE) {
    await db.insert(cash_register_transactions)
      .values(cashBatch.slice(i, i + CHUNK_SIZE))
      .onConflictDoNothing();
  }
  
  // NOTE: payment_gateways_ledger already works since no tough FKs
  for (let i = 0; i < gatewaysBatch.length; i += CHUNK_SIZE) {
    await db.insert(payment_gateways_ledger).values(gatewaysBatch.slice(i, i + CHUNK_SIZE));
  }
}

async function runEtl() {
  console.log("=== INICIANDO BURGERMUSIC FinOps ETL (BATCH BULK V3) ===");
  
  console.log("[ETL] Purgando datos huérfanos anteriores...");
  await db.delete(transactions);
  await db.delete(fact_sales);
  await db.delete(payment_gateways_ledger);
  await db.delete(cash_register_transactions);

  const dicts = await loadDictionaries();
  const ventasExcelPath = path.join(process.cwd(), "Ventas BurgerMusic 18.3.2026.xlsx");
  const dinamicaCsvPath = path.join(process.cwd(), "Dinamica_Burgermusic.csv");

  await ingestSales(ventasExcelPath, dicts);
  await ingestDynamics(dinamicaCsvPath);

  console.log("=== BATCH ETL V3 FINALIZADO CON ÉXITO ===");
  process.exit(0);
}

runEtl().catch(console.error);
