import crypto from "crypto";
import { db } from "./index";
import { products } from "./schema";

const CATALOG_SEED = [
  {
    id: crypto.randomUUID(),
    name: "CLASSIC",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Cheddar, Carne, Cheddar. INCLUYE PAPAS)",
  },
  {
    id: crypto.randomUUID(),
    name: "DUKO",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Cheddar, Panceta, Salsa CUARTO (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "CHARLY",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Cheddar, Cebolla y Salsa Cuarto. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "MALA FAMA",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Cheddar, Panceta, Huevo, Cebolla Caramelizada, Salsa Barbacoa. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "HC (Hernán Cattáneo)",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Cebolla Crispy, Panceta Picada, Doble Cheddar y Salsa Tasty. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "RESIDENTE",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description:
      "Pan de Queso, Provoleta, Queso Dambo, Cebolla Crispy, Salsa Sweet Chili (Picante Dulce). (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "BOB MARLEY",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "cheddar + salsa guacamole. (INCLUYE PAPAS)",
  },
  {
    id: crypto.randomUUID(),
    name: "KISS",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Pan de queso, morrones asados, huevo, cheddar y salsa tasty. (INCLUYE PAPAS)",
  },
  {
    id: crypto.randomUUID(),
    name: "ROLLING STONES",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Cheddar, Cebolla y Morrón Salteados, Salsa Especial. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "RED HOT",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Cheddar, lechuga, tomate, jamon, salsa especial (INCLUYE PAPAS)",
  },
  {
    id: crypto.randomUUID(),
    name: "THE BEATLES",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description:
      'Cheddar, Cebolla Morada, Pepinos, Lechuga, Tomate, Salsa "Big Mac". (INCLUYE PAPAS).',
  },
  {
    id: crypto.randomUUID(),
    name: "AC/DC",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Cheddar, Cebolla Crispy, Panceta, Salsa Barbacoa. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "FRIED ONION",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description:
      "Homenaje a George Motz: Carne Smasheada con Cebolla, Doble Cheddar por Medallón, Mayonesa y Ketchup. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "TECHNO CHICKEN",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description:
      "medallon de pollo, cheddar, lechuga, tomate, cebolla, salsa bigmac. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "GORILLAZ",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Aros de cebolla, panceta, doble Cheddar, salsa cuarto. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "MADONNA Veggie",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description:
      "Medallon veggie a eleccion + Queso, cebolla crispy, tomate, mayonesa not co. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "PATRICIO REY",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Queso Provoleta + oregano, salsa criolla. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "ALMA FUERTE pulled pork",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description:
      "Sandwich de bondiola desmenuzada con Pan de Pizza + cheddar + barbacoa + Papas fritas",
  },
  {
    id: crypto.randomUUID(),
    name: "BIZARRAP Session #1",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description:
      "Medallon de pollo crunch, doble cheddar, panceta, salsa barbacoa. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "BIZARRAP Session #2",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description:
      "Medallón de pollo crunch, cheddar,tomate,lechuga,cebolla y mostaza dulce. (INCLUYE PAPAS).",
  },
  {
    id: crypto.randomUUID(),
    name: "Eminem",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "doble smash, croissant,doble cheddar y panceta",
  },
  {
    id: crypto.randomUUID(),
    name: "KIDS ROCK (menu infantil)",
    category: "BURGER" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "4 unidades Ricosaurios de pollo + Papas individuales",
  },
  {
    id: crypto.randomUUID(),
    name: "Papas QUEEN",
    category: "SIDE" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Cheddar, panceta + verdeo (porcion para 2 personas)",
  },
  {
    id: crypto.randomUUID(),
    name: "Papas Cheddar",
    category: "SIDE" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Papas Baston con Cheddar",
  },
  {
    id: crypto.randomUUID(),
    name: "Papas MERCURY",
    category: "SIDE" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Papas fritas, bondiola de cerdo desmenuzada, barbacoa y verdeo",
  },
  {
    id: crypto.randomUUID(),
    name: "Aros de cebolla + papas",
    category: "SIDE" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Aros de cebolla 12u",
  },
  {
    id: crypto.randomUUID(),
    name: "Nuggets de pollo + papas",
    category: "SIDE" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Nuggets de pollo 12u + papas + dip de barbacoa",
  },
  {
    id: crypto.randomUUID(),
    name: "PICADAS BEAT FREESTYLE",
    category: "SIDE" as const,
    base_price_cents: 0,
    includes_fries: true,
    description: "Papas fritas + Aros de cebolla + Nuggets + Finger de pollo. 4 salsas a eleccion",
  },
  {
    id: crypto.randomUUID(),
    name: "RIHANNA",
    category: "SALAD" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "lechuga, pollo, crutones, queso, aderezo cesar",
  },
  {
    id: crypto.randomUUID(),
    name: "LADY GAGA",
    category: "SALAD" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "rucula, tomate cherry, pollo crunch, queso. Deep de aderezo especial",
  },
  {
    id: crypto.randomUUID(),
    name: "Franui",
    category: "DESSERT" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "Frambuesas bañadas con chocolate",
  },
  {
    id: crypto.randomUUID(),
    name: "tostados clasicos",
    category: "SIDE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "tostado americano + levite",
    category: "SIDE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "tostado de panceta huevo y queso cheddar",
  },
  {
    id: crypto.randomUUID(),
    name: "tostado clasico + levite",
    category: "SIDE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "tostado de jamon y queso",
  },
  {
    id: crypto.randomUUID(),
    name: "X2 tostado americano",
    category: "SIDE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "2 unidades de tostado de panceta huevo y queso cheddar",
  },
  {
    id: crypto.randomUUID(),
    name: "X2 tostado clasico",
    category: "SIDE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "2 unidades de tostado de jamon y queso",
  },
  {
    id: crypto.randomUUID(),
    name: "villavicencio 500cc",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Coca Cola 1.5 lts",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Coca Cola Zero 1.5 Lts",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "SpriTe 1.5 lts",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "lata Sprite 354cc",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "lata Coca-Cola 354cc",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Levite de naranja 500ml",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Levite de manzana 500ml",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Levite de pomelo 500ml",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Levite de pomelo 1,5lt",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Levite de manzana 1.5 lts",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Cerveza Heineken Lata 473cc",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Andes Rubia Lata 473cc",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Andes IPA Lata 473cc",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Stella artois lata",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
  {
    id: crypto.randomUUID(),
    name: "Lata Schweppes Pomelo Zero",
    category: "BEVERAGE" as const,
    base_price_cents: 0,
    includes_fries: false,
    description: "",
  },
];

export async function seedCatalog() {
  await db.insert(products).values(CATALOG_SEED).onConflictDoNothing({ target: products.name });

  console.log("Catálogo inyectado correctamente.");
}
